export const cityList = [
  { key: 'af', value: 'Afghanistan', text: 'Afghanistan' },
  { key: 'al', value: 'Albania', text: 'Albania' },
  { key: 'dz', value: 'Algeria', text: 'Algeria' },
  { key: 'ad', value: 'Andorra', text: 'Andorra' },
  { key: 'ao', value: 'Angola', text: 'Angola' },
  { key: 'ai', value: 'Anguilla', text: 'Anguilla' },
  { key: 'ag', value: 'Antigua', text: 'Antigua' },
  { key: 'ar', value: 'Argentina', text: 'Argentina' },
  { key: 'am', value: 'Armenia', text: 'Armenia' },
  { key: 'aw', value: 'Aruba', text: 'Aruba' },
  { key: 'au', value: 'Australia', text: 'Australia' },
  { key: 'at', value: 'Austria', text: 'Austria' },
  { key: 'az', value: 'Azerbaijan', text: 'Azerbaijan' },
  { key: 'bs', value: 'Bahamas', text: 'Bahamas' },
  { key: 'bh', value: 'Bahrain', text: 'Bahrain' },
  { key: 'bd', value: 'Bangladesh', text: 'Bangladesh' },
  { key: 'bb', value: 'Barbados', text: 'Barbados' },
  { key: 'by', value: 'Belarus', text: 'Belarus' },
  { key: 'be', value: 'Belgium', text: 'Belgium' },
  { key: 'bz', value: 'Belize', text: 'Belize' },
  { key: 'bj', value: 'Benin', text: 'Benin' },
];
